schema_version: 1

context:
  component_name: gui
  repo_name: ${{ "gz-" + component_name }}
  version: 9.0.0
  major_version: "9"
  name: ${{ repo_name + major_version }}
  component_version: ${{ component_name + major_version }}
  cxx_name: ${{ "lib" + name }}
  py_name: ${{ "py" + name }}
  is_python_min: ${{ python_version.split('.')[0:2] | join('.') | float >= 3.8 }}

recipe:
  name: ${{ name }}
  version: ${{ version }}

source:
  - url: https://github.com/gazebosim/${{ repo_name }}/archive/${{ repo_name }}${{ major_version }}_${{ version }}.tar.gz
    sha256: 3b1df7fd30e8b2ffc6d10cda8fb0b3fdc35ce15b3f25b29a13c5e2adf7b49b98

build:
  number: 4

outputs:
  - package:
      name: ${{ cxx_name }}
    build:
      script:
        - if: unix
          then: build_cxx.sh
        - if: win
          then: bld_cxx.bat
      ignore_run_exports:
        by_name:
          - python
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ninja
        - cmake
        - pkg-config
      host:
        - libgz-cmake3
        - libabseil
        - libprotobuf
        - tinyxml2
        - libgz-math7
        - libgz-common5
        - libgz-plugin2
        - libgz-transport13
        - libgz-rendering8
        - libgz-msgs10 >=10.3.2
        - libgz-tools2
        - libgz-utils2
        - qt-main
        - python
        - pybind11
        - pybind11-abi
        - if: linux
          then:
            - libgl-devel
        - if: win
          then:
            - dlfcn-win32
        - ogre 1.10.*
      run_exports:
        - ${{ pin_subpackage(cxx_name, upper_bound='x') }}
    tests:
      - script:
          - if: not win
            then:
              - test -f ${PREFIX}/include/gz/${{ component_version }}/gz/${{ component_name }}.hh
              - test -f ${PREFIX}/lib/cmake/${{ name }}/${{ name }}-config.cmake
          - if: linux
            then:
              - test -f ${PREFIX}/lib/lib${{ name }}.so
          - if: osx
            then:
              - test -f ${PREFIX}/lib/lib${{ name }}.dylib
          - if: win
            then:
              - if not exist %PREFIX%\\Library\\include\\gz\\${{ component_version }}\\gz\\${{ component_name }}.hh exit 1
              - if not exist %PREFIX%\\Library\\lib\\${{ name }}.lib exit 1
              - if not exist %PREFIX%\\Library\\bin\\${{ name }}.dll exit 1
              - if not exist %PREFIX%\\Library\\lib\\cmake\\${{ name }}\\${{ name }}-config.cmake exit 1

  - package:
      name: ${{ py_name }}
    build:
      skip:
        - if: not is_python_min
          then: true
      script:
        - if: unix
          then: build_py.sh
        - if: win
          then: bld_py.bat
    requirements:
      build:
        - python
        - cross-python_${{ target_platform }}
        - ${{ compiler('cxx') }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ninja
        - cmake
        - pkg-config
      host:
        - ${{ pin_subpackage(cxx_name, exact=True) }}
        - python
        - pybind11
        - pybind11-abi
      run:
        - ${{ pin_subpackage(cxx_name, exact=True) }}
        - python
    tests:
      - python:
          imports:
            - gz.gui9

  - package:
      name: ${{ name }}
    requirements:
      run:
        - ${{ pin_subpackage(cxx_name, exact=True) }}
        - if: is_python_min
          then:
            - ${{ pin_subpackage(py_name, exact=True) }}
      run_exports:
        - ${{ pin_subpackage(cxx_name, upper_bound='x') }}
    tests:
      - script:
          - if: not win
            then:
              - test -f ${PREFIX}/include/gz/${{ component_version }}/gz/${{ component_name }}.hh
              - test -f ${PREFIX}/lib/cmake/${{ name }}/${{ name }}-config.cmake
          - if: linux
            then:
              - test -f ${PREFIX}/lib/lib${{ name }}.so
          - if: osx
            then:
              - test -f ${PREFIX}/lib/lib${{ name }}.dylib
          - if: win
            then:
              - if not exist %PREFIX%\\Library\\include\\gz\\${{ component_version }}\\gz\\${{ component_name }}.hh exit 1
              - if not exist %PREFIX%\\Library\\lib\\${{ name }}.lib exit 1
              - if not exist %PREFIX%\\Library\\bin\\${{ name }}.dll exit 1
              - if not exist %PREFIX%\\Library\\lib\\cmake\\${{ name }}\\${{ name }}-config.cmake exit 1
      - python:
          imports:
            - if: is_python_min
              then: gz.gui9

  # Versionless dummy packages, see https://github.com/conda-forge/gz-sim-feedstock/issues/102
  - package:
      name: libgz-${{ component_name }}
    requirements:
      run:
        - ${{ pin_subpackage(cxx_name, exact=true) }}
      run_exports:
        - ${{ pin_subpackage(cxx_name, upper_bound='x') }}
        - ${{ pin_subpackage('libgz-gui', upper_bound='x') }}
    tests:
      - script:
          - cmake-package-check gz-${{ component_name }}${{ major_version }}
        requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}

  - package:
      name: gz-${{ component_name }}-python
    requirements:
      run:
        - ${{ pin_subpackage(python_name, upper_bound='x.x.x') }}
    tests:
      - python:
          imports:
            - gz.${{ component_name }}${{ major_version }}

  - package:
      name: gz-${{ component_name }}
    requirements:
      run:
        - ${{ pin_subpackage(name, exact=true) }}
      run_exports:
        - ${{ pin_subpackage(cxx_name, upper_bound='x') }}
        - ${{ pin_subpackage('libgz-gui', upper_bound='x') }}
    tests:
      - script:
          - cmake-package-check gz-${{ component_name }}${{ major_version }}
        requirements:
          run:
            - cmake-package-check
            - ${{ compiler('c') }}
            - ${{ compiler('cxx') }}
      - python:
          imports:
            - gz.${{ component_name }}${{ major_version }}

about:
  homepage: https://github.com/gazebosim/${{ repo_name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: Builds on top of Qt to provide widgets which are useful when developing robotics applications, such as a 3D view, plots, dashboard, etc, and can be used together in a convenient unified interface.

extra:
  feedstock-name: ${{ repo_name }}
  recipe-maintainers:
    - wolfv
    - traversaro
    - Tobias-Fischer
    - j-rivero
